// codebase
export type PUSH_CODES_HTML = 'PUSH_CODES_HTML';
export const PUSH_CODES_HTML = 'PUSH_CODES_HTML';

export type PUSH_CODES_CSS = 'PUSH_CODES_CSS';
export const PUSH_CODES_CSS = 'PUSH_CODES_CSS';

// staticLibrary

export type ADD_STATIC_COMPONENT = 'ADD_STATIC_COMPONENT';
export const ADD_STATIC_COMPONENT = 'ADD_STATIC_COMPONENT';

export type REMOVE_STATIC_COMPONENT = 'REMOVE_STATIC_COMPONENT';
export const REMOVE_STATIC_COMPONENT = 'REMOVE_STATIC_COMPONENT';

export type MOD_STATIC_COMPONENT = 'MOD_STATIC_COMPONENT';
export const MOD_STATIC_COMPONENT = 'MOD_STATIC_COMPONENT';

export type MOD_STATIC_COMPONENT_NAME = 'MOD_STATIC_COMPONENT_NAME';
export const MOD_STATIC_COMPONENT_NAME = 'MOD_STATIC_COMPONENT_NAME';

export type ADD_STATIC_DATA = 'ADD_STATIC_DATA';
export const ADD_STATIC_DATA = 'ADD_STATIC_DATA';

export type MOD_STATIC_DATA = 'MOD_STATIC_DATA';
export const MOD_STATIC_DATA = 'MOD_STATIC_DATA';

export type REMOVE_STATIC_DATA = 'REMOVE_STATIC_DATA';
export const REMOVE_STATIC_DATA = 'REMOVE_STATIC_DATA';

// global

export type SET_ACTIVE_COMPONENT = 'SET_ACTIVE_COMPONENT';
export const SET_ACTIVE_COMPONENT = 'SET_ACTIVE_COMPONENT';

export type SET_INSPECTING_TYPE = 'SET_INSPECTING_TYPE';
export const SET_INSPECTING_TYPE = 'SET_INSPECTING_TYPE';

export type SET_COMPONENT_TYPE = 'SET_COMPONENT_TYPE';
export const SET_COMPONENT_TYPE = 'SET_COMPONENT_TYPE';

export type SET_LIVE_COMPONENT = 'SET_LIVE_COMPONENT';
export const SET_LIVE_COMPONENT = 'SET_LIVE_COMPONENT';

// live data

export type MOD_LIVE_DATA = 'MOD_LIVE_DATA';
export const MOD_LIVE_DATA = 'MOD_LIVE_DATA';

export type REMOVE_ALL_LIVE_DATA = 'REMOVE_ALL_LIVE_DATA';
export const REMOVE_ALL_LIVE_DATA = 'REMOVE_ALL_LIVE_DATA';

// messages

// export type ADD_MESSAGE = 'ADD_MESSAGE';
// export const ADD_MESSAGE = 'ADD_MESSAGE';

// export type REMOVE_MESSAGE = 'REMOVE_MESSAGE';
// export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';

// export type MOD_MESSAGE = 'MOD_MESSAGE';
// export const MOD_MESSAGE = 'MOD_MESSAGE';

// export type ADD_MESSAGE_ITEM = 'ADD_MESSAGE_ITEM';
// export const ADD_MESSAGE_ITEM = 'ADD_MESSAGE_ITEM';
export type MOD_COMMON_ITEM = 'MOD_COMMON_ITEM';
export const MOD_COMMON_ITEM = 'MOD_COMMON_ITEM';

export type SET_ACTIVE_TEMPLATE = 'SET_ACTIVE_TEMPLATE';
export const SET_ACTIVE_TEMPLATE = 'SET_ACTIVE_TEMPLATE';

export type CHANGE_TEMPLATE = 'CHANGE_TEMPLATE';
export const CHANGE_TEMPLATE = 'CHANGE_TEMPLATE';

export type SET_COMMON_VALUE = 'SET_COMMON_VALUE';
export const SET_COMMON_VALUE = 'SET_COMMON_VALUE';